var questions = [
    {
        "id": "162",
        "ques": "Which concept do we use for the implementation of late binding?",
        "option1": "Static Functions",
        "option2": "Constant Functions",
        "option3": "Operator Functions",
        "option4": "Virtual Functions",
        "correctOption": "D",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "163",
        "ques": "__________ is an ability of grouping certain lines of code that we need to include in our program?",
        "option1": "Macros ",
        "option2": "Modularization",
        "option3": "Program Control ",
        "option4": "Specific Task",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "164",
        "ques": " Which of these keywords do we use for the declaration of the friend function?",
        "option1": "my friend",
        "option2": "class friend",
        "option3": "friend",
        "option4": "fiend",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "165",
        "ques": " What is used for dereferencing?",
        "option1": "pointer with asterix",
        "option2": "pointer without asterix",
        "option3": "value with asterix",
        "option4": "value without asterix",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "166",
        "ques": "what does polymorphism stand for?",
        "option1": "a class that has many forms",
        "option2": "a class \u00a0that has four forms",
        "option3": "a class that has two forms",
        "option4": "a class that has only single form",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "167",
        "ques": "Which of these components are used in a Java program for compilation, debugging, and execution?",
        "option1": "JDK",
        "option2": "JVM",
        "option3": "JRE",
        "option4": "JIT",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "168",
        "ques": "Out of these packages, which one contains an abstract keyword?",
        "option1": "java.lang",
        "option2": "java.util",
        "option3": "java.system",
        "option4": "java.io",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "169",
        "ques": "When an expression consists of int, double, long, float, then the entire expression will get promoted into a data type that is:",
        "option1": "float",
        "option2": "double",
        "option3": "int ",
        "option4": "char",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "170",
        "ques": "Which among these is not Web Browser?",
        "option1": "Chrome",
        "option2": "Opera",
        "option3": "NetSurf",
        "option4": "Brave",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "171",
        "ques": "At which port number, Simple Network Management Protocol (SNMP) operates",
        "option1": "161",
        "option2": "165",
        "option3": "164",
        "option4": "162",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "172",
        "ques": "Evaluate the postfix Expression : 3 5 7 * + 8 2 \/ -",
        "option1": "48",
        "option2": "30",
        "option3": "34",
        "option4": "25",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "173",
        "ques": "Identify the correct extension of the user-defined header file in c++",
        "option1": ".cpp",
        "option2": ".hg",
        "option3": ".h",
        "option4": ".hf",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "174",
        "ques": "Identify the incorrect constructor type.",
        "option1": "Friend Constructor ",
        "option2": "Default Constructor ",
        "option3": "Parameterized Constructor ",
        "option4": "Copy Constructor ",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "175",
        "ques": "C++ use which approach?",
        "option1": "right-left",
        "option2": "Top-down",
        "option3": "right-left",
        "option4": "bottom-up",
        "correctOption": "D",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "176",
        "ques": "Identify the correct syntax for declaring arrays in c++",
        "option1": "arr arr[10]",
        "option2": "array{10}",
        "option3": "int arr[10]",
        "option4": "int arr",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "177",
        "ques": "size of wchat_t is ....",
        "option1": "2",
        "option2": "4",
        "option3": "2 or 4",
        "option4": "Depends on number of bits in system",
        "correctOption": "D",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "178",
        "ques": "Identify the correct example for a pre-increment operator.",
        "option1": "++n",
        "option2": "n++",
        "option3": "- -n",
        "option4": "+n",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "179",
        "ques": "Identify the scope resolution operator.",
        "option1": ":",
        "option2": "::",
        "option3": "?",
        "option4": "None",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "180",
        "ques": "0",
        "option1": "Address of operator",
        "option2": "value of address operator",
        "option3": "Multiplication operator",
        "option4": "All of the above",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "181",
        "ques": "choose the correct default return value of function.",
        "option1": "int ",
        "option2": "void ",
        "option3": "char",
        "option4": " float",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "182",
        "ques": "When can an inline function can expanded?",
        "option1": "Runtime ",
        "option2": "Compile time ",
        "option3": "Never gets expanded ",
        "option4": "All the above",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "183",
        "ques": "Identify the correct function from which the execution of C++ program starts?",
        "option1": "new()",
        "option2": "start()",
        "option3": "pow()",
        "option4": "main()",
        "correctOption": "D",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "184",
        "ques": "The constants in c++ are also known as ?",
        "option1": "pre-processor ",
        "option2": "literals ",
        "option3": "const",
        "option4": "none",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "185",
        "ques": "Using which of the following keywords can an exception be generated ?",
        "option1": "threw ",
        "option2": "throws",
        "option3": "throw",
        "option4": "catch",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "186",
        "ques": "Identify the size of int datatype in C++ ?",
        "option1": "1 byte",
        "option2": "2 bytes",
        "option3": "4 bytes",
        "option4": "Depends on compiler",
        "correctOption": "D",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "187",
        "ques": "choose the size of the below struct. Struct { int a; charb; float c; }",
        "option1": "2",
        "option2": "4",
        "option3": "7",
        "option4": "10",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "188",
        "ques": "Identify the logical AND operator.      ",
        "option1": "||",
        "option2": "&&",
        "option3": "&",
        "option4": "!",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "189",
        "ques": "Choose the correct subscript operator.",
        "option1": "[]",
        "option2": "{}",
        "option3": "&",
        "option4": "()",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "190",
        "ques": "Choose the type of loop which is guaranteed to execute at-least once?",
        "option1": "for loop",
        "option2": "do-while",
        "option3": "while ",
        "option4": "None",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "191",
        "ques": "  How much bytes of memory does void occupy?",
        "option1": "1",
        "option2": "0",
        "option3": "2",
        "option4": "4",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "192",
        "ques": " Why are comments used?",
        "option1": "Make the program run faster",
        "option2": "To help others read & understand program",
        "option3": "increase the size of the program",
        "option4": "make a program compiler easier",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "193",
        "ques": "Total types of errors in C++.",
        "option1": "1",
        "option2": "2",
        "option3": "3",
        "option4": "4",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "194",
        "ques": " Identify the storage classes that have global visibility.",
        "option1": "extern",
        "option2": "auto ",
        "option3": "register",
        "option4": "static",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "195",
        "ques": "Total types of constructors in C++ are?",
        "option1": "1",
        "option2": "2",
        "option3": "3",
        "option4": "4",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "196",
        "ques": "What is the number of parameters that a default constructor requires?",
        "option1": "3",
        "option2": "2",
        "option3": "1",
        "option4": "0",
        "correctOption": "D",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "197",
        "ques": " What does a C++ class hold?",
        "option1": "Function",
        "option2": "Data ",
        "option3": "Arrays",
        "option4": "Both A and B",
        "correctOption": "D",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "198",
        "ques": "  Data members and member functions of a class are private by.default. True or False?",
        "option1": "true",
        "option2": "false ",
        "option3": "Depends on code",
        "option4": "None",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "199",
        "ques": " Under which pillar of OOPS does base class and derived class relationship come?",
        "option1": "Polymorphism",
        "option2": "Inheritance",
        "option3": "Encapsulation",
        "option4": "Abstraction",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "200",
        "ques": "Which of the following functions can be inherited from base class?",
        "option1": "Constructor ",
        "option2": "Destructor ",
        "option3": "Static",
        "option4": "None",
        "correctOption": "D",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "201",
        "ques": "Identify the correct escape sequence used for the new line.",
        "option1": "slace t",
        "option2": "slace n",
        "option3": "slace a",
        "option4": "None",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "202",
        "ques": "Which of the following is not a type of inheritance?",
        "option1": "Multiple ",
        "option2": "Multilevel",
        "option3": "Distributed",
        "option4": "Heirrarchical",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "203",
        "ques": "  What is an object in c++?",
        "option1": "it is function of class",
        "option2": "it is instance of class",
        "option3": "it is Datatype  of class",
        "option4": "it is part of the syntax of class.",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "204",
        "ques": "Choose the correct option which is mandatory in a function.",
        "option1": "return_type",
        "option2": "parameters",
        "option3": "function_name",
        "option4": "Both a and c",
        "correctOption": "D",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "205",
        "ques": "C++ language was developed by ___.",
        "option1": "Dennis Rechard",
        "option2": "Dennis M. Ritchie",
        "option3": "Bjarne Stroustrup",
        "option4": "Anders Hejlsberg",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "206",
        "ques": "In which year, the name of the language was changed from \"C with Classes\" to C++?",
        "option1": "1983",
        "option2": "1986",
        "option3": "1989",
        "option4": "1976",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "207",
        "ques": "C++ language is a successor to which language?",
        "option1": "B",
        "option2": "C",
        "option3": "Java",
        "option4": "python",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "208",
        "ques": "C++ language is a ___.",
        "option1": "Object Oriented Language",
        "option2": "Procedural Oriented Language",
        "option3": "Structural Oriented Language",
        "option4": "None of the above",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "209",
        "ques": "C++ is a ___.",
        "option1": "High-level language",
        "option2": "Medium level language",
        "option3": "Low-level language",
        "option4": "None of the Above",
        "correctOption": "B",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "210",
        "ques": "How many keywords are in C++?",
        "option1": "32",
        "option2": "45",
        "option3": "35",
        "option4": "54",
        "correctOption": "A",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    },
    {
        "id": "211",
        "ques": "Which of the following language translator is used in C++?",
        "option1": "Assembler ",
        "option2": "Interpreter",
        "option3": "Compiler",
        "option4": "Both Interpreter and Compiler",
        "correctOption": "C",
        "quizName": "CodingExam",
        "quizStartTime": "2023-07-22 08:25:00",
        "quizEndTime": "2023-07-23 08:25:00",
        "adminEmail": "mohdnasir@gmail.com"
    }
];